Docs/8 documentar semana 6
fga-eps-mds/2024.1-PrintGo-Doc pull request #10
Opened 2024-05-02 00:51 UTC by anajbsouza

2024-05-08 00:19 UTC, lbvx requested changes

2024-05-08 00:19 UTC, lbvx commented on docs/atas/24-04.md
> +- O foco do MVP vai ser capturar informações dos equipamentos usando o protocolo SNP. Outras funcionalidades serão implementadas a partir desta.
SNMP, não SNP

2024-07-12 21:07 UTC, GRVial commented on docs/atas/24-04.md
> +- O foco do MVP vai ser capturar informações dos equipamentos usando o protocolo SNP. Outras funcionalidades serão implementadas a partir desta.
@anajbsouza @MatheussBrant No aguardo para fechar o PR

2024-07-14 23:33 UTC, GRVial approved these changes

2024-07-14 23:34 UTC, GRVial commented on docs/atas/24-04.md
> +- O foco do MVP vai ser capturar informações dos equipamentos usando o protocolo SNP. Outras funcionalidades serão implementadas a partir desta.
Arrumei 👍

2024-07-14 23:35 UTC, merged