Adiciona  Visão de Produto ao documento principal
fga-eps-mds/2024.1-PrintGo-Doc pull request #51
Opened 2024-07-15 15:40 UTC by CA1RO

relacionado a issue #15

2024-07-15 19:35 UTC, GRVial requested changes
Corrigir os comentários apenas. 👌

2024-07-15 19:35 UTC, GRVial commented on mkdocs.yml
> +    - Lean Inception: visaoproduto/VisaoDoProduto
Faltou a extensão do arquivo.

- Lean Inception: **visaoproduto/VisaoDoProduto.md**

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +Nessa etapa é definido a essência e valor de negócio do produto, de uma maneira clara e convincente para os clientes. Dessa forma, a visão de produto auxilia a trilhar um caminho inicial, definindo a
Nessa etapa são definidos a essência e o valor de negócio...

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +Essa atividade serve para esclarecer as limitações do produto em relação ao que ele é (É/Não é) e ao que ele faz (Faz/Não faz). Sendo assim, ao final dessa atividade os participantes possuem uma visã
em relação **às** funcionalidades...

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +- Uma onda não pode conter três cartões somente amarelos ouvermelhos.
amarelos ou vermelhos

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +- A soma de valor dos cartões não pode ser menos de quatro “$” equatro corações.
faltou espaço **e quatro**

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +Abaixo, o sequeciador realizado, em reunião, pela equipe junto aos clientes:
**sequenciador**

2024-07-15 19:35 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +Ao final do Lean Inception, é feito o Canvas MVP, que é uma representação visual que resume o MVP, juntando todas as estapas abordadas anteriormente. Finalmente, resulta no seguinte quadro feito pela
**etapas**

2024-07-15 19:38 UTC, GRVial commented
Lembrando de utilizar a política de commits e pull request corretamente, segue link do [Guia de Contribuição](https://fga-eps-mds.github.io/2024.1-PrintGo-Doc/inicio/guia_contribuicao/).

2024-07-16 01:32 UTC, GRVial requested changes

2024-07-16 01:32 UTC, GRVial commented on docs/visaoproduto/VisaoDoProduto.md
> +Essa atividade serve para esclarecer as limitações do produto em relação às funcionalidades, respondendo o que ele é (É/Não é) e o que ele faz (Faz/Não faz). Sendo assim, ao final dessa atividade os
Vc arrumou no lugar errado. É ali no fim do parágrafo que ta faltando a crase

2024-07-16 01:32 UTC, GRVial commented on mkdocs.yml
>    - Definição do Produto:
Altera de Definição do Produto para Visão do Produto.

2024-07-16 13:32 UTC, CA1RO commented
Alterações feitas.

2024-07-16 16:58 UTC, lbvx requested changes
Só corrigir o comentário e arrumar o conflito e aí 🚀

2024-07-16 16:58 UTC, lbvx commented on docs/visaoproduto/VisaoDoProduto.md
> +![grafico](../assets/leaninception/graficoEsforco.png)
Nessas imagens que não são nossas, favor colocar a fonte na legenda da imagem, centralizado à página.

2024-07-16 17:28 UTC, DanielViniciusAlves submitted a review, later dismissed

2024-07-17 00:37 UTC, lbvx approved these changes
É isso aí! Valeu!

2024-07-18 13:22 UTC, GRVial approved these changes

2024-07-18 13:22 UTC, merged