[Docs] - Plano de custos
fga-eps-mds/2024.1-PrintGo-Doc pull request #63
Opened 2024-07-19 21:24 UTC by GRVial

### Descrição 
Criação do plano de custos do projeto

### Checklist
- [ ] Documento de plano de custos
- [ ] Planilha de custos

Closes: #60

2024-07-20 16:41 UTC, lbvx requested changes

2024-07-20 16:41 UTC, lbvx commented on docs/plano-monitoramento/plano-custos.md
> +&emsp;&emsp;Foi utilizado o custo médio anual por aluno de instituto federal. De acordo com o [Jornal da UNESP](https://jornal.unesp.br/2022/06/08/cobranca-de-mensalidade-nao-e-a-solucao-para-o-finan
Colocar o ano que esses dados forem coletados pra dar melhor contexto pro parágrafo seguinte

2024-07-20 16:41 UTC, lbvx commented on docs/plano-monitoramento/plano-custos.md
> +&emsp;&emsp;Considerando as estimativas de custos feitas, o orçamento  inicial total estimado para o projeto em 11 semanas é de R$ 133.973,49.
tem 2 espaços depois de "orçamento" 🤣

2024-07-20 16:48 UTC, lbvx approved these changes

2024-07-22 22:49 UTC, DanielViniciusAlves approved these changes

2024-07-23 17:21 UTC, merged