Docs/visao logica de dados
fga-eps-mds/2024.1-PrintGo-Doc pull request #70
Opened 2024-07-25 23:29 UTC by lbvx

### Descrição 
Adiciona visão lógica de dados ao doc de arquitetura, incluindo MERs e DLDs

closes #69

2024-07-27 02:26 UTC, GRVial requested changes

2024-07-27 02:26 UTC, GRVial commented on docs/documentos-projeto/arquitetura.md
> +    - ativo
- IMPRESSORA:
    id Int @id @default(autoincrement())
    numContrato String
    numSerie String @unique
    enderecoIp String @unique
    estaNaRede Boolean
    dataInstalacao DateTime
    dataRetirada DateTime?
    ativo Boolean
    contadorInstalacaoPB Int
    contadorInstalacaoCor Int
    contadorAtualPB Int
    contadorAtualCor Int
    contadorRetiradaPB Int
    contadorRetiradaCor Int
    localizacao String
    modeloId String

2024-07-27 16:20 UTC, lbvx commented on docs/documentos-projeto/arquitetura.md
> +    - ativo
Arrumado!

2024-07-28 19:56 UTC, DanielViniciusAlves approved these changes

2024-07-29 01:12 UTC, GRVial approved these changes

2024-07-29 01:13 UTC, merged