Docs/sprint 1 2
fga-eps-mds/2024.1-PrintGo-Doc pull request #87
Opened 2024-08-08 22:40 UTC by GRVial

### Descrição 
Adiciona andamento das Sprints 1 e 2.

### Checklist

- [ ] Andamento Sprint 1
- [ ] Andamento Sprint 2

Issue relacionada: closes #77 e #86

2024-08-11 21:55 UTC, lbvx requested changes

2024-08-11 21:55 UTC, lbvx commented on docs/andamento/sprint1.md
> +-
tem um bullet point vazio aqui

2024-08-15 20:16 UTC, GRVial commented on docs/andamento/sprint1.md
> +-
Corrigido

2024-08-15 20:21 UTC, lbvx approved these changes

2024-08-15 20:21 UTC, merged